export const REPORT_COLUMNS = [
  "Booking ID",
  "Booked On",
  "Booking Initiator Name",
  "Booking Initiator Email",
  "Booking Initiator Phone",
  "Department",
  "Guest's Address",
  "Pincode",
  "City",
  "State",
  "Purpose",
  "Justification",
  "Guest Names",
  "Guest List",
  "Arrival Date",
  "Arrival Time",
  "Departure Date",
  "Departure Time",
  "No. of stay days",
  "Meal Plan",
  "Extra Bed",
  "Room Configuration",
  "Room Selection",
  "Rooms Required",
  "Services required",
  "Food Reservations",
  "Male Count",
  "Female Count",
  "Children Count",
  "Total Guests",
  "Booking Cost Center",
  "Estimated Cost",
  "Special requests",
  "Approval Status",
  "Estate Status",
  "Cancellation Remarks",
] as const;

export type ReportColumn = (typeof REPORT_COLUMNS)[number];

